name: 'Build and Deploy App'

on:
    push:
        tags:
            - 'v-*'

jobs:
    deploy:
        name: Deploy Production App
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Use NodeJS 20
              uses: actions/setup-node@v5
              with:
                  node-version: '20'

            - name: Set env file
              env:
                  ENV: ${{ secrets.PROD_ENV }}
              run: cd $GITHUB_WORKSPACE/server && echo "$ENV" >| .env

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push
              id: docker_build
              uses: docker/build-push-action@v6
              with:
                  context: ./
                  file: ./Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tcc-production:latest

            - name: Image digest
              run: echo ${{ steps.docker_build.outputs.digest }}

            - name: Pull and run docker container on Droplet
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  script: |
                      docker pull tamsclubcalendar/tcc-production:latest
                      docker stop production && docker run --rm -d --name production -p 8082:80 -p 8084:90 tamsclubcalendar/tcc-production
                      docker image prune -af
